trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePhpVersion@0
  inputs:
    versionSpec: '8.1' # or 8.x, depending on your PHP version
    installationPath: '/usr/local/php'

- script: |
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"
  displayName: 'Install Composer'

- script: |
    php composer.phar install --no-interaction --prefer-dist --optimize-autoloader
  displayName: 'Install Dependencies'

- script: |
    php artisan key:generate
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
  displayName: 'Prepare Laravel'

- task: AzureRmWebAppDeployment@4
  inputs:
    azureSubscription: 'd7dda821-25b5-479e-9b8c-131e47953176'
    appType: 'webApp'
    appName: 'atthehouseorgapi'
    package: '$(System.DefaultWorkingDirectory)'
